//USING THIS HEADER GUARD TO MAKE SURE THAT THE HEADER FILE IS INCLUDED ONLY ONCE. THE '#ifndef' PREPROCESSOR DIRECTIVE CHECKS IF THE
//HEADER FILE IS DEFINED OR NOT. IF IT IS NOT DEFINED THEN IT DEFINES IT IN THE SUBSEQUENT LINES AND IF IT IS ALREADY THEN IT SKIPS IT.
//THIS ENSURES THAT THE HEADER IS INCLUDED ONLY ONCE PER TRANSLATION UNIT(THE FINAL CODE AFTER RESOLVING ALL MACROS AND HEADER)
#ifndef MAZE_HPP
#define MAZE_HPP

//INCLUDING DEPENDENCIES
#include <vector>
#include <string>

using namespace std;

//MADE A VERY EFFICIENT IMPLEMENTATION OF 2D POINTS
struct Point2D 
{
    //MEMBER VARIABLES
    int x, y;
    
    //CONSTRUCTOR
    //USING AN INITIALIZER LIST ISNTEAD OF ASSIGNING VALUES IN THE CONSTRUCTOR BODY BECAUSE DOING IT THAT WAY FIRST INITALIZES 
    //THE VARIABLE TO A GARBAGE VALUE AND THEN OVERWRITES IT WITH THE VALUE WE WANT TO ASSIGN. THE INITIALIZER LIST DIRECTLY
    //ASSIGNS THE PASSED VALUES TO THE MEBER VARIABLES
    Point2D(int x_ = 0, int y_ = 0) : x(x_), y(y_) {} 
};
 
class Maze2D 
{
private:

    int rows, cols;
    
    vector<vector<int>> grid;

public:

    explicit Maze2D(const string& filename);

    bool isValidMove(int x, int y) const;

    int getRows() const;
    int getCols() const;

    void printMaze() const;

    const vector<vector<int>>& getGrid() const { return grid; }
};

//CLASS DEFINITION/INTERFACE FOR 'Path1D'
class Path1D 
{
//INCASPTULATING THE 'moves' VECTOR SO THAT IT CAN ONLY BE ACCESSED BY THE MEMBER FUNCTIONS OF THE CLASS
private:

    vector<int> moves; //THIS WILL BE POPULATED DURING THE IMPLEMENTATION OF THE CONSTRUCTOR TO HOLD THE PATH PROVIDED IN THE FILE

//MEMBER FUNCTIONS
public:

    //CUNSTRUCTOR
    //USING EXPLICIT BECAUSE IT WAS NOT CONVERTING THE PATHFILE TO 'Path1D' OBJECT IMPLICITLY AND I DON'T KNOW WHY. SO I TRIED TO 
    //MAKE IT EXPLICITLY CONVERTIBLE WHILE INSTANTIATING THE OBJECT AND IT WORKED
    explicit Path1D(const string& filename); 

    //THIS FUNCTION VALIDATES THE PATH FROM 'moves'(POPULATED FROM THE PATH FILE WHEN THE OBJECT IS INSTANTIATED) AND VALDIATES IT AGAINST THE MAZE
    //THE PROVIDED MAZE AND 'pathTrace' IS POPULATED WHICH IS REQUIRED LATER. 
    bool isValidPath(const Maze2D& maze, vector<Point2D>& pathTrace) const; //USING 'const' AS A FAILSAFE SO THAT THE FUNCTION DOESN'T MODIFY THE OBJECT
};

//MARKS THE END OF THE HEADER GUARD
#endif
